Implemented patient creation
TekClinic/Patients-MicroService pull request #8
Opened 2024-03-31 10:39 UTC by Whitomtit

This method is a gRPC version of [POST /patient](https://tekclinic.github.io/API-Gateway/#/Patient/createPatient) endpoint.

It's a milestone for completion of the first criteria in TekClinic/backlog#28.

2024-03-31 20:08 UTC, vMaroon requested changes

2024-03-31 20:08 UTC, vMaroon commented on server/server.go
> +// If some argument is missing or not valid, codes.InvalidArgument is returned.
Add a dot after each sentence (or whichever grammatically correct form you want).

2024-03-31 20:08 UTC, vMaroon commented on server/server.go
> +		return nil, status.Error(codes.Unauthenticated, err.Error())
(Relevant for most errors) I mentioned this in a PR I approved and merged: what are the conventions on handling errors in these cases? Should they not be logged?

2024-03-31 22:30 UTC, Whitomtit commented on server/server.go
> +		return nil, status.Error(codes.Unauthenticated, err.Error())
@vMaroon Since we are reporting to gRPC, we can setup a middleware for the whole server that will log all errors and successful calls:
![image](https://github.com/TekClinic/Patients-MicroService/assets/57540985/b6fd08b9-8c45-4bae-96a8-12e446bd97c3)

Above is an example of how it works. I can open an issue to add these logger capabilities to Microservice-Lib and to use them in all microservices.

2024-04-01 11:25 UTC, vMaroon approved these changes

2024-04-01 11:25 UTC, merged